// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mysql_connect.Data;

#nullable disable

namespace mysql_connect.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230607114134_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Mmysql_connect.Models.Book", b =>
            {
                b.Property<int>("no")
                    .HasColumnType("int");

                b.Property<string>("judulbuku")
                    .IsRequired()
                    .HasColumnType("varchar(50)");

                b.Property<string>("pengarang")
                    .IsRequired()
                    .HasColumnType("varchar(50)");

                b.Property<string>("harga")
                    .IsRequired()
                    .HasColumnType("int");

                b.Property<string>("penerbit")
                    .IsRequired()
                    .HasColumnType("varchar(50)");
                b.Property<string>("kategori")
                    .IsRequired()
                    .HasColumnType("varchar(50)");
                b.Property<string>("gambar")
                    .HasColumnType("varchar(30)");

                b.HasKey("no");

                b.ToTable("tb_buku");
            });


#pragma warning restore 612, 618
        }
    }
}
